export const __prod__ = process.env.NODE_ENV === 'production';
export const PORT = 5000;
export const PG_PORT = 5432;
export const REDIS_PORT = 6379;
export const NODE_ENV = 'development';
export const COOKIE_NAME = 'wid';
export const FORGET_PASSWORD_PREFIX = 'forget-password:';
export const SESSION_SECRET = 'DalmatiansRKool';
export const DATABASE_TYPE = 'postgresql';
export const DB_TYPE = 'postgres';
export const PG_DATABASE = 'awad_full_stack';
export const PG_USER = 'postgres';
export const PG_PASSWORD = 'My2dogs95';
export const PG_HOST = 'localhost';
